Repository AChillFeeder/ProjetSansNom-Back, pull requests merged in 2025-03, with the labels that each got.

#3 Dev
  controllers/annoncesController.js
  controllers/usersController.js
  db/db_config.js
  index.js
  routes/annonces.js
  routes/users.js
Labels: Fonctionnalité

#4 bugfix hosting clever cloud - db_config
  controllers/annoncesController.js
Labels: Bugfix

#5 bugfix cors
  package-lock.json
  package.json
Labels: Bugfix

#6 bugfix packages and controller
  index.js
  package-lock.json
  package.json
Labels: Bugfix

#7 bugfix port issue
  index.js
Labels: Bugfix

#8 healthcheck
  index.js
Labels: Bugfix

#10 Dev
  controllers/annoncesController.js
  controllers/usersController.js
  db/db_config.js
  index.js
  routes/annonces.js
Labels: Fonctionnalité, Release

#11 correction usersController
  controllers/usersController.js
Labels: Bugfix

#13 CRUD annonces
  controllers/annoncesController.js
Labels: Fonctionnalité

#15 Dev
  controllers/usersController.js
  routes/users.js
Labels: Fonctionnalité

#18 rajout des routes pour la messagerie
  controllers/annoncesController.js
  controllers/conversationsController.js
  controllers/messagesController.js
  controllers/usersController.js
  db/db_config.js
  index.js
  package-lock.json
  package.json
  routes/conversations.js
  routes/messages.js
  routes/users.js
Labels: Bugfix, Fonctionnalité

#19 Gestion favoris
  controllers/favorisController.js
  index.js
  routes/favoris.js
Labels: Fonctionnalité

#20 Dev
  controllers/annoncesController.js
  controllers/favorisController.js
  index.js
  routes/favoris.js
Labels: Bugfix, Fonctionnalité
